### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by reinkepatrick** [deep-green/deep-green#13]
- [x] Repositories anlegen __(Marti)__
    - [x] KI 1
    - [x] KI 2
    - [x] Backend
    - [x] Computer Vision
    - [x] Frontend
    - [x] Alexa
    - [x] Google Home
- [ ] Schnittstellen Definition
    - [x] Künstliche Intelligenz __(Patrick, Marti, Luis und Phillip)__
    - [ ] Voice Assistent __(Max, Julien und Alex)__
    - [ ] Backend __(Hendrik und Tobias)__
    - [ ] Computer Vision __(Torsten)__
    - [ ] Frontend __(Nicola)__
- [x] Server aufsetzen __(Patrick)__
- [x] MongoDB Atlas __(Patrick)__
- [x] TravisCI __(Marti)__
- [ ] Pflichtenheft
- [ ] Überschriften Mockups __(Nicola)__
- [ ] Zustandsdiagramm
- [ ] Klassendiagramm __(Hendrik)__
- [ ] Use-Cases überprüfen
    - [x] Künstliche Intelligenz __(Patrick, Marti, Luis und Phillip)__
    - [x] Voice Assistent __(Max, Julien und Alex)__
    - [ ] Backend __(Hendrik und Tobias)__
    - [x] Computer Vision __(Torsten)__
    - [ ] Frontend __(Nicola)__
- [x] Verfahrensmatrix __(Torsten)__
